name: run main.py

on:
  schedule:
    -cron 0 8 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install Python packages
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute Python script
        env:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          redirect_uri: ${{ secrets.REDIRECT_URI }}
          bearer_token: ${{ secrets.BEARER_TOKEN }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          source_playlist_id: ${{ secrets.SOURCE_PLAYLIST_ID }}
          destination_playlist_id: ${{ secrets.DESTINATION_PLAYLIST_ID }}
        run: python main.py
